name: Build PyAudio

on:
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.14']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install PortAudio (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y portaudio19-dev python3-dev

    - name: Install PortAudio (macOS)
      if: runner.os == 'macOS'
      run: |
        brew install portaudio

    - name: Install PortAudio (Windows)
      if: runner.os == 'Windows'
      run: |
        vcpkg install portaudio:x64-windows-static
      shell: bash

    - name: Install build tools
      run: python -m pip install --upgrade pip setuptools wheel

    - name: Build PyAudio (Linux and macOS)
      if: runner.os != 'Windows'
      run: python setup.py bdist_wheel

    - name: Build PyAudio (Windows)
      if: runner.os == 'Windows'
      run: |
        $env:VCPKG_PATH = "$env:VCPKG_INSTALLATION_ROOT\installed\x64-windows-static"
        python setup.py bdist_wheel
      shell: pwsh

    - name: Upload ready files
      uses: actions/upload-artifact@v6
      with:
        name: pyaudio-wheels-${{ matrix.os }}
        path: dist/*.whl
